### ISSUE TITLE
Albert_xl2-v2

### ISSUE THREAD

**Issue by garkavem** [pohanchi/huggingface_albert#2]
Hi, thanks for your work! I would like to download the weights Albert_xl2-v2 finetuned on Squad, but as I understand the experiments are still running? I also wonder if they are compatible with Huggingface's AlbertForQuestionAnswering?

**Comment by pohanchi** [comment]
Hi, actually I didn’t run for that experiment. But for squad 1.1 2.0 for
base xlarge v1-v2 it will have a sufficient performance and all of them
didn’t have any error. And My work is an unofficial version work for
huggingface.

So the class I build is my function version.It didn’t compatible for
Huggingface.

But In fact, my class didn’t have any error on that. And reproduce the
equal performance for the origin performance.

I can hand by hand make the Albert-xxlarge vetsion2 pretrained model for u
to download. As I know that I didn’t have a sufficient gpu storage to run
that and actually I think xlarge have a sufficient performance on squad 1.1
2.0 so I didn’t make it. If u want to use it ,you can follow the above
issue step by step download the tf-hub version and using my convert tf to
pytorch python code to have a pretrained weight for u to train.

**Comment by garkavem** [comment]
Ok, thanks a lot!
